Fixes dynamic release checks

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-set -e
+set -ex
 
 exec 3>&1 # make stdout available as fd 3 for the result
 exec 1>&2 # redirect all output to stderr for logging
@@ -30,8 +30,8 @@ elif [ -n "$namespace_overwrite" ]; then
   namespace=$namespace_overwrite
 fi
 
-if [ -z "$namespace" ]; then
-  release="$current_namespace"
+if [ -n "$current_namespace" ]; then
+  namespace="$current_namespace"
 fi
 
 if [ -f "$source/$release_overwrite" ]; then
@@ -47,12 +47,12 @@ fi
 if [ "$release" ] ; then
   revision=$($helm_bin history --max 20 --namespace $namespace $release 2>/dev/null | grep -i 'deployed' | awk '{print $1}' )
   if [ "$revision" ] ; then
-    echo $revision | jq -R '.' | jq -s "map({\"revision\": ., \"release\": \"$release\"})" >&3
+    echo $revision | jq -R '.' | jq -s "map({\"revision\": ., \"release\": \"$release\", \"namespace\": \"$namespace\"})" >&3
     exit 0
   fi
 fi
 
 # if we get here we couldnt find a revision to return so we bail - this is a good thing
 # since check should fail if its configuration cant point to a verifiable state.
-echo "Unable to confirm any revision for namspace: $namespace & release: $release" 
+echo "Unable to confirm any revision for namespace: $namespace & release: $release" 
 exit 1
